[package]
name = "midas"
version = "0.5.2"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Do painless migration."
categories = ["command-line-utilities", "development-tools", "embedded"]
homepage = "https://github.com/ffimnsr/midas"
repository = "https://github.com/ffimnsr/midas"
license = "MIT OR Apache-2.0"
keywords = ["migrations", "database", "postgres", "migrate", "cli"]
exclude = [".gitignore"]

[dependencies]
clap = "2.33"
postgres = "0.19"
regex = "1.5"
failure = "0.1"
env_logger = "0.8"
log = "0.4"
url = "2.2"

[dev-dependencies]
tempfile = "3.2"
