[package]
name = "midas"
version = "0.4.0"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Do painless migration."
homepage = "https://github.com/ffimnsr/midas"
repository = "https://github.com/ffimnsr/midas"
license = "MIT"
keywords = ["migrations", "database", "postgres", "migrate", "cli"]

[dependencies]
clap = "2.33"
postgres = "0.16.0-rc.2"
regex = "1.2"
failure = "0.1"
env_logger = "0.6"
log = "0.4"
url = "2.1"
fallible-iterator = "0.2"

[dev-dependencies]
tempfile = "3.1"
